# ──────────────────────────────────────────────────────────────────────────────
# compiler/indexgen.jl — Wiki index generation for LLMWiki.jl
# ──────────────────────────────────────────────────────────────────────────────
#
# Auto-generates wiki/index.md from all wiki pages, categorised by PageType.

"""
    generate_index!(config::WikiConfig)

Auto-generate `wiki/index.md` from all wiki pages.

Pages are grouped into categories (Concepts, Entities, Queries, Overview)
based on their `page_type` frontmatter field.  Each entry is formatted as:

    - [Title](concepts/slug.md) — summary

Orphaned pages are listed in a separate section.
"""
function generate_index!(config::WikiConfig)
    categories = Dict{PageType, Vector{NamedTuple{(:title,:slug,:summary,:path,:orphaned), Tuple{String,String,String,String,Bool}}}}()
    for pt in instances(PageType)
        categories[pt] = []
    end
    orphaned_entries = NamedTuple{(:title,:slug,:summary,:path), Tuple{String,String,String,String}}[]

    # Scan concept pages
    _scan_pages_for_index!(categories, orphaned_entries, config, config.concepts_dir, "concepts")

    # Scan query pages
    _scan_pages_for_index!(categories, orphaned_entries, config, config.queries_dir, "queries")

    # Build the markdown
    buf = IOBuffer()
    println(buf, "# Wiki Index\n")
    println(buf, "_Auto-generated by LLMWiki.jl — do not edit manually._\n")

    category_names = Dict{PageType, String}(
        CONCEPT   => "Concepts",
        ENTITY    => "Entities",
        QUERY_PAGE => "Queries",
        OVERVIEW  => "Overview",
    )

    for pt in (OVERVIEW, CONCEPT, ENTITY, QUERY_PAGE)
        entries = categories[pt]
        isempty(entries) && continue
        # Filter out orphaned entries from main categories
        live = filter(e -> !e.orphaned, entries)
        isempty(live) && continue

        sort!(live; by=e -> lowercase(e.title))
        println(buf, "## $(category_names[pt])\n")
        for e in live
            summary_part = isempty(e.summary) ? "" : " — $(e.summary)"
            println(buf, "- [$(e.title)]($(e.path)/$(e.slug).md)$(summary_part)")
        end
        println(buf)
    end

    # Orphaned section
    if !isempty(orphaned_entries)
        sort!(orphaned_entries; by=e -> lowercase(e.title))
        println(buf, "## Orphaned Pages\n")
        for e in orphaned_entries
            println(buf, "- ~~[$(e.title)]($(e.path)/$(e.slug).md)~~ _(orphaned)_")
        end
        println(buf)
    end

    index_path = joinpath(config.root, config.index_file)
    mkpath(dirname(index_path))
    atomic_write(index_path, String(take!(buf)))
    @info "Regenerated index" path=index_path
end

"""
    _scan_pages_for_index!(categories, orphaned, config, dir, rel_path)

Helper: scan all `.md` files in `dir` and populate the categories and
orphaned lists with their metadata.
"""
function _scan_pages_for_index!(categories, orphaned_entries, config::WikiConfig,
                                 dir::String, rel_path::String)
    full_dir = if isabspath(dir) dir else joinpath(config.root, dir) end
    isdir(full_dir) || return

    for f in readdir(full_dir)
        endswith(f, ".md") || continue
        content = safe_read(joinpath(full_dir, f))
        content === nothing && continue

        meta, _ = parse_frontmatter(content)
        slug = replace(f, ".md" => "")
        entry = (title=meta.title, slug=slug, summary=meta.summary,
                 path=rel_path, orphaned=meta.orphaned)

        if meta.orphaned
            push!(orphaned_entries, (title=meta.title, slug=slug,
                                     summary=meta.summary, path=rel_path))
        end

        if haskey(categories, meta.page_type)
            push!(categories[meta.page_type], entry)
        else
            push!(categories[CONCEPT], entry)
        end
    end
end
